version: '3.8'

services:
  db:
    image: postgres:15
    container_name: sosguinee_db
    environment:
      - POSTGRES_DB=sosguinee
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SEREma@2024
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    container_name: sosguinee_web
    command: gunicorn sosguinee.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - USE_POSTGRES=True
      - POSTGRES_NAME=sosguinee
      - POSTGRES_DB=sosguinee
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SEREma@2024
      - POSTGRES_PORT=5432
      - ALLOWED_HOSTS=127.0.0.1,localhost,18.170.114.4
    depends_on:
      - db
    restart: always

volumes:
  pgdata:
  static_volume:
  media_volume:
