
upstream django {
    server web:8000;
}

server {
    listen 80;
    server_name 18.170.114.4;

    # Logs
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Gère les fichiers statiques (CSS, JS, images)
    location /static/ {
        alias /app/staticfiles/;
        autoindex off;
    }

    # Gère les fichiers médias (uploads)
    location /media/ {
        alias /app/mediafiles/;
        autoindex off;
    }

    # Gère l'accès à Django (admin compris)
    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # (Optionnel) Renforce la sécurité HTTP
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options DENY;
    add_header Referrer-Policy strict-origin-when-cross-origin;
}

