# Generated by Django 4.1.13 on 2024-07-25 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Statut Financement',
                'verbose_name_plural': 'Statuts Financements',
                'db_table': 'funding_request_status',
            },
        ),
        migrations.CreateModel(
            name='FundingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Type Financement',
                'verbose_name_plural': 'Types Financements',
                'db_table': 'funding_type',
            },
        ),
        migrations.CreateModel(
            name='LossAlertStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Statut alerte perte',
                'verbose_name_plural': 'Statuts alerte perte',
                'db_table': 'loss_alert_status',
            },
        ),
        migrations.CreateModel(
            name='LossAlertType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Type alerte perte',
                'verbose_name_plural': 'Types alerte perte',
                'db_table': 'loss_alert_type',
            },
        ),
        migrations.CreateModel(
            name='OptionalAlertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='img/alerts/')),
            ],
            options={
                'verbose_name': 'Image alerte perte',
                'verbose_name_plural': 'Images alerte perte',
                'db_table': 'optional_alert_image',
            },
        ),
        migrations.CreateModel(
            name='OptionalImageFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='img/Fundings/')),
            ],
            options={
                'verbose_name': 'Image Financement',
                'verbose_name_plural': 'Images Financements',
                'db_table': 'optional_image_funding',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('civility', models.CharField(blank=True, choices=[('', 'Choisir civilité'), ('Mme', 'Madame'), ('Mr', 'Monsieur')], max_length=5, null=True, verbose_name='Civilité')),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('id_card', models.FileField(blank=True, null=True, upload_to='user_images/id_cards')),
                ('id_card_type', models.CharField(blank=True, max_length=100, null=True)),
                ('id_card_country', models.CharField(blank=True, choices=[('', 'Choisir Pays'), ('FR', 'France'), ('US', "États-Unis d'Amérique"), ('ES', 'Espagne'), ('GB', 'Royaume-Uni'), ('CA', 'Canada'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('JP', 'Japon'), ('AU', 'Australie'), ('BR', 'Brésil'), ('IN', 'Inde'), ('CH', 'Chine'), ('NL', 'Pays-Bas'), ('MX', 'Mexique'), ('AR', 'Argentine'), ('IE', 'Irlande'), ('RU', 'Russie'), ('GN', 'Guinée'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('ZA', 'Afrique du Sud'), ('KE', 'Kenya'), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('LR', 'Libéria'), ('CM', 'Cameroun'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('SL', 'Sierra-Leone'), ('GM', 'Gambie')], max_length=100, null=True)),
                ('birth_piece', models.FileField(blank=True, null=True, upload_to='user_images/birth_piece')),
                ('birth_piece_country', models.CharField(blank=True, choices=[('', 'Choisir Pays'), ('FR', 'France'), ('US', "États-Unis d'Amérique"), ('ES', 'Espagne'), ('GB', 'Royaume-Uni'), ('CA', 'Canada'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('JP', 'Japon'), ('AU', 'Australie'), ('BR', 'Brésil'), ('IN', 'Inde'), ('CH', 'Chine'), ('NL', 'Pays-Bas'), ('MX', 'Mexique'), ('AR', 'Argentine'), ('IE', 'Irlande'), ('RU', 'Russie'), ('GN', 'Guinée'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('ZA', 'Afrique du Sud'), ('KE', 'Kenya'), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('LR', 'Libéria'), ('CM', 'Cameroun'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('SL', 'Sierra-Leone'), ('GM', 'Gambie')], max_length=100, null=True)),
                ('person_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_images/photos')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, choices=[('', 'Choisir profession'), ('TECHNICIAN', 'Technicien'), ('PROFESSIONAL', 'Professionnel'), ('OTHER', 'Autre')], max_length=100, null=True, verbose_name='Profession')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('actual_country', models.CharField(blank=True, choices=[('', 'Choisir Pays'), ('FR', 'France'), ('US', "États-Unis d'Amérique"), ('ES', 'Espagne'), ('GB', 'Royaume-Uni'), ('CA', 'Canada'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('JP', 'Japon'), ('AU', 'Australie'), ('BR', 'Brésil'), ('IN', 'Inde'), ('CH', 'Chine'), ('NL', 'Pays-Bas'), ('MX', 'Mexique'), ('AR', 'Argentine'), ('IE', 'Irlande'), ('RU', 'Russie'), ('GN', 'Guinée'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('ZA', 'Afrique du Sud'), ('KE', 'Kenya'), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('LR', 'Libéria'), ('CM', 'Cameroun'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('SL', 'Sierra-Leone'), ('GM', 'Gambie')], max_length=100, null=True)),
                ('birth_country', models.CharField(blank=True, choices=[('', 'Choisir Pays'), ('FR', 'France'), ('US', "États-Unis d'Amérique"), ('ES', 'Espagne'), ('GB', 'Royaume-Uni'), ('CA', 'Canada'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('JP', 'Japon'), ('AU', 'Australie'), ('BR', 'Brésil'), ('IN', 'Inde'), ('CH', 'Chine'), ('NL', 'Pays-Bas'), ('MX', 'Mexique'), ('AR', 'Argentine'), ('IE', 'Irlande'), ('RU', 'Russie'), ('GN', 'Guinée'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('ZA', 'Afrique du Sud'), ('KE', 'Kenya'), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('LR', 'Libéria'), ('CM', 'Cameroun'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('SL', 'Sierra-Leone'), ('GM', 'Gambie')], max_length=100, null=True)),
                ('is_actual_country_as_birth_country', models.BooleanField(default=True)),
                ('phone_code', models.CharField(blank=True, max_length=5, null=True)),
                ('profession_situation', models.CharField(blank=True, choices=[('', 'Choisir situation professionnelle'), ('EMPLOYED', 'Employé'), ('UNEMPLOYED', 'Sans emploi'), ('OTHER', 'Autre')], max_length=100, null=True)),
                ('activity_sector', models.CharField(blank=True, choices=[('', "Choisir secteur d'activité"), ('AGRICULTURE', 'Agriculture'), ('CONSTRUCTION', 'Construction'), ('INDUSTRIAL', 'Industrielle'), ('COMMERCE', 'Commerce'), ('TECHNOLOGY', 'Technologie'), ('OTHER', 'Autre')], max_length=100, null=True)),
                ('high_education', models.CharField(blank=True, choices=[('', 'Choisir dernier diplôme'), ('BACCALAUREAT', 'Baccalauréat'), ('BTS', 'BTS'), ('LICENCE', 'Licence'), ('MASTER', 'Master'), ('DOCTORAT', 'Doctorat'), ('OTHER', 'Autre')], max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('', 'Choisir Pays'), ('FR', 'France'), ('US', "États-Unis d'Amérique"), ('ES', 'Espagne'), ('GB', 'Royaume-Uni'), ('CA', 'Canada'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('JP', 'Japon'), ('AU', 'Australie'), ('BR', 'Brésil'), ('IN', 'Inde'), ('CH', 'Chine'), ('NL', 'Pays-Bas'), ('MX', 'Mexique'), ('AR', 'Argentine'), ('IE', 'Irlande'), ('RU', 'Russie'), ('GN', 'Guinée'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('ZA', 'Afrique du Sud'), ('KE', 'Kenya'), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('LR', 'Libéria'), ('CM', 'Cameroun'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('SL', 'Sierra-Leone'), ('GM', 'Gambie')], max_length=100, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=100, null=True)),
                ('actual_city', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('user_type', models.CharField(choices=[('Creator', 'Creator'), ('Backer', 'Backer')], default='Creator', max_length=20)),
                ('user_category', models.CharField(blank=True, choices=[('', 'Choisir catégorie'), ('PPHYSIQUE', 'Physique'), ('PMORALE', 'Morale')], max_length=20, null=True)),
                ('user_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detail Utilisateur',
                'verbose_name_plural': 'Details Utilisateurs',
                'db_table': 'user_details',
            },
        ),
        migrations.CreateModel(
            name='LossAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('principal_image', models.ImageField(upload_to='img/alerts/')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, default='Guinée', max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('quarter', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('date_alert', models.DateField()),
                ('hour_alert', models.TimeField(blank=True, null=True)),
                ('loss_alert_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='page.lossalertstatus')),
                ('loss_alert_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='page.lossalerttype')),
                ('optional_images', models.ManyToManyField(blank=True, to='page.optionalalertimage')),
            ],
            options={
                'verbose_name': 'Alerte perte',
                'verbose_name_plural': 'Alertes perte',
                'db_table': 'loss_alert',
            },
        ),
        migrations.CreateModel(
            name='FundingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('funding_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description_needs', models.TextField()),
                ('principal_image', models.ImageField(upload_to='img/Fundings/')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, default='Guinée', max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('quarter', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('funding_request_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='page.fundingrequeststatus')),
                ('funding_request_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='page.fundingtype')),
                ('optional_images', models.ManyToManyField(blank=True, to='page.optionalimagefunding')),
            ],
            options={
                'verbose_name': 'Demande Financement',
                'verbose_name_plural': 'Demandes Financements',
                'db_table': 'funding_request',
            },
        ),
    ]
