# Generated by Django 5.0.7 on 2024-07-31 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_messagecontact_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='fundingrequest',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='fundingrequest',
            name='beneficiary_name',
            field=models.CharField(max_length=255, verbose_name='Nom Beneficiaire'),
        ),
        migrations.AlterField(
            model_name='fundingrequest',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='fundingrequest',
            name='description_needs',
            field=models.TextField(verbose_name='Description besoins'),
        ),
        migrations.AlterField(
            model_name='fundingrequest',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='fundingrequest',
            name='funding_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant Financement'),
        ),
        migrations.AlterField(
            model_name='fundingrequest',
            name='funding_request_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='page.fundingtype', verbose_name='Type Financement'),
        ),
        migrations.AlterField(
            model_name='fundingrequest',
            name='optional_images',
            field=models.ManyToManyField(blank=True, to='page.optionalimagefunding', verbose_name='Images Secondaires'),
        ),
        migrations.AlterField(
            model_name='fundingrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='fundingrequest',
            name='principal_image',
            field=models.ImageField(upload_to='img/Fundings/', verbose_name='Image Principale'),
        ),
        migrations.AlterField(
            model_name='fundingrequest',
            name='quarter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Quartier'),
        ),
        migrations.AlterField(
            model_name='fundingrequeststatus',
            name='description',
            field=models.TextField(verbose_name='Description Statut Financement'),
        ),
        migrations.AlterField(
            model_name='fundingrequeststatus',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Statut Financement'),
        ),
        migrations.AlterField(
            model_name='fundingtype',
            name='description',
            field=models.TextField(verbose_name='Description Type Financement'),
        ),
        migrations.AlterField(
            model_name='fundingtype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Type Financement'),
        ),
        migrations.AlterField(
            model_name='lossalert',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='lossalert',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='lossalert',
            name='country',
            field=models.CharField(blank=True, default='Guinée', max_length=255, null=True, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='lossalert',
            name='date_alert',
            field=models.DateField(verbose_name='Date alerte perte'),
        ),
        migrations.AlterField(
            model_name='lossalert',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='lossalert',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='lossalert',
            name='hour_alert',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure alerte perte'),
        ),
        migrations.AlterField(
            model_name='lossalert',
            name='loss_alert_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='page.lossalerttype', verbose_name='Type alerte perte'),
        ),
        migrations.AlterField(
            model_name='lossalert',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='lossalert',
            name='optional_images',
            field=models.ManyToManyField(blank=True, related_name='loss_alerts', to='page.optionalalertimage'),
        ),
        migrations.AlterField(
            model_name='lossalert',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='lossalert',
            name='principal_image',
            field=models.ImageField(upload_to='img/alerts/', verbose_name='Image Principale'),
        ),
        migrations.AlterField(
            model_name='lossalert',
            name='quarter',
            field=models.CharField(max_length=255, verbose_name='Quartier'),
        ),
        migrations.AlterField(
            model_name='lossalertstatus',
            name='description',
            field=models.TextField(verbose_name='Description Statut alerte perte'),
        ),
        migrations.AlterField(
            model_name='lossalertstatus',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Statut alerte perte'),
        ),
        migrations.AlterField(
            model_name='lossalerttype',
            name='description',
            field=models.TextField(verbose_name='Description Type alerte perte'),
        ),
        migrations.AlterField(
            model_name='lossalerttype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Type alerte perte'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sujet'),
        ),
        migrations.AlterField(
            model_name='optionalimagefunding',
            name='image',
            field=models.ImageField(upload_to='img/Fundings/', verbose_name='Image Principale'),
        ),
    ]
