# Generated by Django 5.0.7 on 2024-08-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_donation_amount_alter_donation_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subjet', models.TextField(blank=True, null=True, verbose_name='Object du message')),
                ('plain_message', models.TextField(blank=True, null=True, verbose_name='Message Texte')),
                ('sender_email', models.TextField(blank=True, null=True, verbose_name='Envoyeur')),
                ('html_message', models.TextField(blank=True, null=True, verbose_name='Message Html')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='lossalert',
            name='principal_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/alerts/', verbose_name='Image Principale'),
        ),
        migrations.AlterField(
            model_name='optionalalertimage',
            name='image',
            field=models.ImageField(upload_to='img/alerts/', verbose_name='Autres images'),
        ),
        migrations.AlterField(
            model_name='optionalimagefunding',
            name='image',
            field=models.ImageField(upload_to='img/Fundings/', verbose_name='Autres images'),
        ),
    ]
