# Generated by Django 5.0.7 on 2024-08-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_emailcontent_alter_lossalert_principal_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcontent',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcontent',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
