# Generated by Django 5.0.7 on 2024-08-18 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_emailcontent_date_sent_emailcontent_is_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailcontent',
            options={'verbose_name': 'Email', 'verbose_name_plural': 'Emails'},
        ),
        migrations.AddField(
            model_name='donation',
            name='date_donation',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Don'),
        ),
        migrations.AddField(
            model_name='fundingrequest',
            name='ending_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Financement'),
        ),
        migrations.AddField(
            model_name='fundingrequest',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Demande'),
        ),
        migrations.AddField(
            model_name='messagecontact',
            name='date_contact',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de contact'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='emailcontent',
            table='email_content',
        ),
    ]
