# Generated by Django 5.0.7 on 2024-08-18 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_alter_emailcontent_options_donation_date_donation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundingrequest',
            name='ending_date',
        ),
        migrations.AddField(
            model_name='fundingrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date debut Financement'),
        ),
        migrations.AddField(
            model_name='fundingrequest',
            name='title',
            field=models.CharField(default='Demande de Financement', max_length=255, verbose_name='Intitulé Financement'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='date_donation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Don'),
        ),
        migrations.AlterField(
            model_name='fundingrequest',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date fin Demande'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='date_contact',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date de contact'),
        ),
    ]
