# Generated by Django 5.0.7 on 2024-08-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_remove_fundingrequest_ending_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingrequest',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Intitulé Financement'),
        ),
    ]
