# Generated by Django 5.0.7 on 2024-08-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_alter_fundingrequest_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingrequest',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant reçu'),
        ),
    ]
