# Generated by Django 5.0.7 on 2024-08-27 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_fundingrequest_amount_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalAlertDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='img/alerts/', verbose_name='Autres documents')),
            ],
            options={
                'verbose_name': "Autre documents d'alerte perte",
                'verbose_name_plural': "Autres documents d' alerte perte",
                'db_table': 'optional_alert_doc',
            },
        ),
        migrations.CreateModel(
            name='OptionalFundingDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(upload_to='img/Fundings/', verbose_name='Autres documents')),
            ],
            options={
                'verbose_name': 'Autre document de Financement',
                'verbose_name_plural': 'Autres documents de Financements',
                'db_table': 'optional_docs_funding',
            },
        ),
        migrations.RemoveField(
            model_name='lossalert',
            name='optional_images',
        ),
        migrations.RemoveField(
            model_name='fundingrequest',
            name='optional_images',
        ),
        migrations.AlterField(
            model_name='fundingrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Fin Financement'),
        ),
        migrations.AlterField(
            model_name='fundingrequest',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Debut Demande'),
        ),
        migrations.AddField(
            model_name='lossalert',
            name='optional_docs',
            field=models.ManyToManyField(blank=True, related_name='loss_alerts', to='page.optionalalertdoc'),
        ),
        migrations.AddField(
            model_name='fundingrequest',
            name='optional_docs',
            field=models.ManyToManyField(blank=True, to='page.optionalfundingdoc', verbose_name='Autres documents'),
        ),
        migrations.DeleteModel(
            name='OptionalAlertImage',
        ),
        migrations.DeleteModel(
            name='OptionalImageFunding',
        ),
    ]
