# Generated by Django 5.0.7 on 2024-08-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_optionalalertdoc_optionalfundingdoc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingrequest',
            name='optional_docs',
            field=models.ManyToManyField(blank=True, related_name='funding_request_docs', to='page.optionalfundingdoc', verbose_name='Autres documents'),
        ),
        migrations.AlterField(
            model_name='lossalert',
            name='optional_docs',
            field=models.ManyToManyField(blank=True, related_name='loss_alerts_docs', to='page.optionalalertdoc'),
        ),
    ]
