# Generated by Django 5.0.7 on 2024-08-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_alter_fundingrequest_optional_docs_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='optionalfundingdoc',
            table='optional_funding_doc',
        ),
    ]
