# Generated by Django 5.0.7 on 2024-08-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_alter_optionalfundingdoc_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionalalertdoc',
            name='image',
        ),
        migrations.RemoveField(
            model_name='optionalfundingdoc',
            name='image',
        ),
        migrations.AddField(
            model_name='optionalalertdoc',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='img/alerts/', verbose_name='Autres documents'),
        ),
        migrations.AddField(
            model_name='optionalfundingdoc',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='img/Fundings/', verbose_name='Autres documents'),
        ),
    ]
