# Generated by Django 5.0.7 on 2024-08-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_remove_optionalalertdoc_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionalalertdoc',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom document'),
        ),
        migrations.AddField(
            model_name='optionalalertdoc',
            name='document_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Taille document'),
        ),
        migrations.AddField(
            model_name='optionalalertdoc',
            name='document_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type document'),
        ),
        migrations.AddField(
            model_name='optionalfundingdoc',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom document'),
        ),
        migrations.AddField(
            model_name='optionalfundingdoc',
            name='document_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Taille document'),
        ),
        migrations.AddField(
            model_name='optionalfundingdoc',
            name='document_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type document'),
        ),
    ]
