# Generated by Django 5.0.7 on 2024-08-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_optionalalertdoc_document_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingrequest',
            name='optional_docs',
            field=models.ManyToManyField(blank=True, related_name='funding_request', to='page.optionalfundingdoc', verbose_name='Autres documents'),
        ),
        migrations.AlterField(
            model_name='lossalert',
            name='optional_docs',
            field=models.ManyToManyField(blank=True, related_name='loss_alert', to='page.optionalalertdoc'),
        ),
    ]
