# Generated by Django 5.2.1 on 2025-05-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_alter_fundingrequest_optional_docs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingrequeststatus',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Statut Financement'),
        ),
        migrations.AlterField(
            model_name='fundingtype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Type Financement'),
        ),
        migrations.AlterField(
            model_name='lossalertstatus',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Statut alerte perte'),
        ),
        migrations.AlterField(
            model_name='lossalerttype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Type alerte perte'),
        ),
    ]
