# Generated by Django 5.2.1 on 2025-05-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_alter_fundingrequeststatus_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('orange_money', 'Orange Money'), ('paypal', 'PayPal'), ('autre', 'Autre')], default='paypal', max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AddField(
            model_name='donation',
            name='reference',
            field=models.CharField(default='<function now at 0x0000023169AE9580>', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('réussi', 'Réussi'), ('échoué', 'Échoué')], default='en_attente', max_length=20),
        ),
    ]
