# Generated by Django 5.2.1 on 2025-07-13 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_alter_donation_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lossalert',
            name='optional_docs',
            field=models.ManyToManyField(blank=True, related_name='loss_alert', to='page.optionalalertdoc', verbose_name='Autres documents'),
        ),
        migrations.CreateModel(
            name='FundingRequestNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(verbose_name='Message de notification')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_notification', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de notification')),
                ('funding_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='page.fundingrequest', verbose_name='Demande de financement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification de demande de financement',
                'verbose_name_plural': 'Notifications de demandes de financement',
                'db_table': 'funding_request_notification',
            },
        ),
        migrations.CreateModel(
            name='FundPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('orange_money', 'Orange Money'), ('paypal', 'PayPal'), ('autre', 'Autre')], default='PayCard', max_length=20, verbose_name='Méthode de paiement')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('réussi', 'Réussi'), ('échoué', 'Échoué')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('reference', models.CharField(blank=True, help_text='Référence unique pour le paiement', max_length=100, null=True, unique=True, verbose_name='Référence de paiement')),
                ('date_payment', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de paiement')),
                ('funding_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='page.fundingrequest', verbose_name='Demande de financement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_payments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Paiement de financement',
                'verbose_name_plural': 'Paiements de financements',
                'db_table': 'fund_payment',
            },
        ),
        migrations.CreateModel(
            name='LossAlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(verbose_name='Message de notification')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_notification', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de notification')),
                ('loss_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='page.lossalert', verbose_name='Alerte de perte')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Notification d'alerte de perte",
                'verbose_name_plural': "Notifications d'alertes de perte",
                'db_table': 'loss_alert_notification',
            },
        ),
    ]
