# Generated by Django 5.2.1 on 2025-07-15 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_alter_lossalert_optional_docs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse Donateur'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ville Donateur'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pays Donateur'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Donateur'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom Donateur'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom Donateur'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone Donateur'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_quarter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Quartier Donateur'),
        ),
        migrations.AddField(
            model_name='fundpayment',
            name='donor_adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse Donateur'),
        ),
        migrations.AddField(
            model_name='fundpayment',
            name='donor_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ville Donateur'),
        ),
        migrations.AddField(
            model_name='fundpayment',
            name='donor_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pays Donateur'),
        ),
        migrations.AddField(
            model_name='fundpayment',
            name='donor_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Donateur'),
        ),
        migrations.AddField(
            model_name='fundpayment',
            name='donor_first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom Donateur'),
        ),
        migrations.AddField(
            model_name='fundpayment',
            name='donor_last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom Donateur'),
        ),
        migrations.AddField(
            model_name='fundpayment',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone Donateur'),
        ),
        migrations.AddField(
            model_name='fundpayment',
            name='donor_quarter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Quartier Donateur'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='method',
            field=models.CharField(choices=[('paycard', 'PayCard'), ('stripe', 'Stripe'), ('orange_money', 'Orange Money'), ('paypal', 'PayPal'), ('autre', 'Autre')], default='paypal', max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='fundingrequestnotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funding_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='fundpayment',
            name='payment_method',
            field=models.CharField(choices=[('paycard', 'PayCard'), ('stripe', 'Stripe'), ('orange_money', 'Orange Money'), ('paypal', 'PayPal'), ('autre', 'Autre')], default='PayCard', max_length=20, verbose_name='Méthode de paiement'),
        ),
    ]
