# Generated by Django 5.2.1 on 2025-07-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0020_donation_donor_adresse_donation_donor_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor_country',
            field=models.CharField(blank=True, choices=[('', 'Choisir Pays'), ('FR', 'France'), ('US', "États-Unis d'Amérique"), ('ES', 'Espagne'), ('GB', 'Royaume-Uni'), ('CA', 'Canada'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('JP', 'Japon'), ('AU', 'Australie'), ('BR', 'Brésil'), ('IN', 'Inde'), ('CH', 'Chine'), ('NL', 'Pays-Bas'), ('MX', 'Mexique'), ('AR', 'Argentine'), ('IE', 'Irlande'), ('RU', 'Russie'), ('GN', 'Guinée'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('ZA', 'Afrique du Sud'), ('KE', 'Kenya'), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('LR', 'Libéria'), ('CM', 'Cameroun'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('SL', 'Sierra-Leone'), ('GM', 'Gambie')], max_length=255, null=True, verbose_name='Pays Donateur'),
        ),
    ]
