# Generated by Django 5.2.1 on 2025-07-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0021_alter_donation_donor_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='date_donation',
            new_name='donation_date',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donor_adresse',
            new_name='donor_address',
        ),
        migrations.RenameField(
            model_name='fundpayment',
            old_name='donor_adresse',
            new_name='donor_address',
        ),
        migrations.RenameField(
            model_name='fundpayment',
            old_name='date_payment',
            new_name='payment_date',
        ),
        migrations.AddField(
            model_name='fundpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Transaction'),
        ),
    ]
