# Generated by Django 5.2.1 on 2025-07-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0022_rename_date_donation_donation_donation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Transaction'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_country',
            field=models.CharField(blank=True, choices=[('FR', 'France'), ('US', "États-Unis d'Amérique"), ('ES', 'Espagne'), ('GB', 'Royaume-Uni'), ('CA', 'Canada'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('JP', 'Japon'), ('AU', 'Australie'), ('BR', 'Brésil'), ('IN', 'Inde'), ('CH', 'Chine'), ('NL', 'Pays-Bas'), ('MX', 'Mexique'), ('AR', 'Argentine'), ('IE', 'Irlande'), ('RU', 'Russie'), ('GN', 'Guinée'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('ZA', 'Afrique du Sud'), ('KE', 'Kenya'), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('LR', 'Libéria'), ('CM', 'Cameroun'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('SL', 'Sierra-Leone'), ('GM', 'Gambie')], max_length=255, null=True, verbose_name='Pays Donateur'),
        ),
        migrations.AlterField(
            model_name='fundpayment',
            name='donor_country',
            field=models.CharField(blank=True, choices=[('FR', 'France'), ('US', "États-Unis d'Amérique"), ('ES', 'Espagne'), ('GB', 'Royaume-Uni'), ('CA', 'Canada'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('JP', 'Japon'), ('AU', 'Australie'), ('BR', 'Brésil'), ('IN', 'Inde'), ('CH', 'Chine'), ('NL', 'Pays-Bas'), ('MX', 'Mexique'), ('AR', 'Argentine'), ('IE', 'Irlande'), ('RU', 'Russie'), ('GN', 'Guinée'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('ZA', 'Afrique du Sud'), ('KE', 'Kenya'), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('LR', 'Libéria'), ('CM', 'Cameroun'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('SL', 'Sierra-Leone'), ('GM', 'Gambie')], max_length=255, null=True, verbose_name='Pays Donateur'),
        ),
        migrations.AlterField(
            model_name='fundpayment',
            name='donor_first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Prenom Donateur'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='actual_country',
            field=models.CharField(blank=True, choices=[('FR', 'France'), ('US', "États-Unis d'Amérique"), ('ES', 'Espagne'), ('GB', 'Royaume-Uni'), ('CA', 'Canada'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('JP', 'Japon'), ('AU', 'Australie'), ('BR', 'Brésil'), ('IN', 'Inde'), ('CH', 'Chine'), ('NL', 'Pays-Bas'), ('MX', 'Mexique'), ('AR', 'Argentine'), ('IE', 'Irlande'), ('RU', 'Russie'), ('GN', 'Guinée'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('ZA', 'Afrique du Sud'), ('KE', 'Kenya'), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('LR', 'Libéria'), ('CM', 'Cameroun'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('SL', 'Sierra-Leone'), ('GM', 'Gambie')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='birth_country',
            field=models.CharField(blank=True, choices=[('FR', 'France'), ('US', "États-Unis d'Amérique"), ('ES', 'Espagne'), ('GB', 'Royaume-Uni'), ('CA', 'Canada'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('JP', 'Japon'), ('AU', 'Australie'), ('BR', 'Brésil'), ('IN', 'Inde'), ('CH', 'Chine'), ('NL', 'Pays-Bas'), ('MX', 'Mexique'), ('AR', 'Argentine'), ('IE', 'Irlande'), ('RU', 'Russie'), ('GN', 'Guinée'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('ZA', 'Afrique du Sud'), ('KE', 'Kenya'), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('LR', 'Libéria'), ('CM', 'Cameroun'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('SL', 'Sierra-Leone'), ('GM', 'Gambie')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='birth_piece_country',
            field=models.CharField(blank=True, choices=[('FR', 'France'), ('US', "États-Unis d'Amérique"), ('ES', 'Espagne'), ('GB', 'Royaume-Uni'), ('CA', 'Canada'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('JP', 'Japon'), ('AU', 'Australie'), ('BR', 'Brésil'), ('IN', 'Inde'), ('CH', 'Chine'), ('NL', 'Pays-Bas'), ('MX', 'Mexique'), ('AR', 'Argentine'), ('IE', 'Irlande'), ('RU', 'Russie'), ('GN', 'Guinée'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('ZA', 'Afrique du Sud'), ('KE', 'Kenya'), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('LR', 'Libéria'), ('CM', 'Cameroun'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('SL', 'Sierra-Leone'), ('GM', 'Gambie')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='id_card_country',
            field=models.CharField(blank=True, choices=[('FR', 'France'), ('US', "États-Unis d'Amérique"), ('ES', 'Espagne'), ('GB', 'Royaume-Uni'), ('CA', 'Canada'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('JP', 'Japon'), ('AU', 'Australie'), ('BR', 'Brésil'), ('IN', 'Inde'), ('CH', 'Chine'), ('NL', 'Pays-Bas'), ('MX', 'Mexique'), ('AR', 'Argentine'), ('IE', 'Irlande'), ('RU', 'Russie'), ('GN', 'Guinée'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('ZA', 'Afrique du Sud'), ('KE', 'Kenya'), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('LR', 'Libéria'), ('CM', 'Cameroun'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('SL', 'Sierra-Leone'), ('GM', 'Gambie')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='nationality',
            field=models.CharField(blank=True, choices=[('FR', 'France'), ('US', "États-Unis d'Amérique"), ('ES', 'Espagne'), ('GB', 'Royaume-Uni'), ('CA', 'Canada'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('JP', 'Japon'), ('AU', 'Australie'), ('BR', 'Brésil'), ('IN', 'Inde'), ('CH', 'Chine'), ('NL', 'Pays-Bas'), ('MX', 'Mexique'), ('AR', 'Argentine'), ('IE', 'Irlande'), ('RU', 'Russie'), ('GN', 'Guinée'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('ZA', 'Afrique du Sud'), ('KE', 'Kenya'), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('LR', 'Libéria'), ('CM', 'Cameroun'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('SL', 'Sierra-Leone'), ('GM', 'Gambie')], max_length=100, null=True),
        ),
    ]
