# Generated by Django 5.2.1 on 2025-07-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0023_donation_transaction_id_alter_donation_donor_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='reference',
            field=models.CharField(blank=True, help_text='Référence unique pour le don', max_length=100, null=True, unique=True, verbose_name='Référence de don'),
        ),
    ]
