# Generated by Django 5.2.1 on 2025-07-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0025_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
