# Generated by Django 5.2.1 on 2025-07-19 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0026_comment_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commentaire', 'verbose_name_plural': 'Commentaires'},
        ),
    ]
