# Generated by Django 5.2.1 on 2025-07-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0030_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=0, default=0.0, max_digits=5, null=True),
        ),
    ]
