# Generated by Django 5.2.1 on 2025-07-22 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0031_comment_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor_country',
            field=models.CharField(blank=True, choices=[('GN', 'Guinée'), ('FR', 'France'), ('US', "États-Unis d'Amérique"), ('ES', 'Espagne'), ('GB', 'Royaume-Uni'), ('CA', 'Canada'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('JP', 'Japon'), ('AU', 'Australie'), ('BR', 'Brésil'), ('IN', 'Inde'), ('CH', 'Chine'), ('NL', 'Pays-Bas'), ('MX', 'Mexique'), ('AR', 'Argentine'), ('IE', 'Irlande'), ('RU', 'Russie'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('ZA', 'Afrique du Sud'), ('KE', 'Kenya'), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('LR', 'Libéria'), ('CM', 'Cameroun'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('SL', 'Sierra-Leone'), ('GM', 'Gambie')], max_length=255, null=True, verbose_name='Pays Donateur'),
        ),
        migrations.AlterField(
            model_name='fundpayment',
            name='donor_country',
            field=models.CharField(blank=True, choices=[('GN', 'Guinée'), ('FR', 'France'), ('US', "États-Unis d'Amérique"), ('ES', 'Espagne'), ('GB', 'Royaume-Uni'), ('CA', 'Canada'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('JP', 'Japon'), ('AU', 'Australie'), ('BR', 'Brésil'), ('IN', 'Inde'), ('CH', 'Chine'), ('NL', 'Pays-Bas'), ('MX', 'Mexique'), ('AR', 'Argentine'), ('IE', 'Irlande'), ('RU', 'Russie'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('ZA', 'Afrique du Sud'), ('KE', 'Kenya'), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('LR', 'Libéria'), ('CM', 'Cameroun'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('SL', 'Sierra-Leone'), ('GM', 'Gambie')], max_length=255, null=True, verbose_name='Pays Donateur'),
        ),
        migrations.AlterField(
            model_name='lossalert',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom du sujet concerné'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='actual_country',
            field=models.CharField(blank=True, choices=[('GN', 'Guinée'), ('FR', 'France'), ('US', "États-Unis d'Amérique"), ('ES', 'Espagne'), ('GB', 'Royaume-Uni'), ('CA', 'Canada'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('JP', 'Japon'), ('AU', 'Australie'), ('BR', 'Brésil'), ('IN', 'Inde'), ('CH', 'Chine'), ('NL', 'Pays-Bas'), ('MX', 'Mexique'), ('AR', 'Argentine'), ('IE', 'Irlande'), ('RU', 'Russie'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('ZA', 'Afrique du Sud'), ('KE', 'Kenya'), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('LR', 'Libéria'), ('CM', 'Cameroun'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('SL', 'Sierra-Leone'), ('GM', 'Gambie')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='birth_country',
            field=models.CharField(blank=True, choices=[('GN', 'Guinée'), ('FR', 'France'), ('US', "États-Unis d'Amérique"), ('ES', 'Espagne'), ('GB', 'Royaume-Uni'), ('CA', 'Canada'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('JP', 'Japon'), ('AU', 'Australie'), ('BR', 'Brésil'), ('IN', 'Inde'), ('CH', 'Chine'), ('NL', 'Pays-Bas'), ('MX', 'Mexique'), ('AR', 'Argentine'), ('IE', 'Irlande'), ('RU', 'Russie'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('ZA', 'Afrique du Sud'), ('KE', 'Kenya'), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('LR', 'Libéria'), ('CM', 'Cameroun'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('SL', 'Sierra-Leone'), ('GM', 'Gambie')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='birth_piece_country',
            field=models.CharField(blank=True, choices=[('GN', 'Guinée'), ('FR', 'France'), ('US', "États-Unis d'Amérique"), ('ES', 'Espagne'), ('GB', 'Royaume-Uni'), ('CA', 'Canada'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('JP', 'Japon'), ('AU', 'Australie'), ('BR', 'Brésil'), ('IN', 'Inde'), ('CH', 'Chine'), ('NL', 'Pays-Bas'), ('MX', 'Mexique'), ('AR', 'Argentine'), ('IE', 'Irlande'), ('RU', 'Russie'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('ZA', 'Afrique du Sud'), ('KE', 'Kenya'), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('LR', 'Libéria'), ('CM', 'Cameroun'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('SL', 'Sierra-Leone'), ('GM', 'Gambie')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='id_card_country',
            field=models.CharField(blank=True, choices=[('GN', 'Guinée'), ('FR', 'France'), ('US', "États-Unis d'Amérique"), ('ES', 'Espagne'), ('GB', 'Royaume-Uni'), ('CA', 'Canada'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('JP', 'Japon'), ('AU', 'Australie'), ('BR', 'Brésil'), ('IN', 'Inde'), ('CH', 'Chine'), ('NL', 'Pays-Bas'), ('MX', 'Mexique'), ('AR', 'Argentine'), ('IE', 'Irlande'), ('RU', 'Russie'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('ZA', 'Afrique du Sud'), ('KE', 'Kenya'), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('LR', 'Libéria'), ('CM', 'Cameroun'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('SL', 'Sierra-Leone'), ('GM', 'Gambie')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='nationality',
            field=models.CharField(blank=True, choices=[('GN', 'Guinée'), ('FR', 'France'), ('US', "États-Unis d'Amérique"), ('ES', 'Espagne'), ('GB', 'Royaume-Uni'), ('CA', 'Canada'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('JP', 'Japon'), ('AU', 'Australie'), ('BR', 'Brésil'), ('IN', 'Inde'), ('CH', 'Chine'), ('NL', 'Pays-Bas'), ('MX', 'Mexique'), ('AR', 'Argentine'), ('IE', 'Irlande'), ('RU', 'Russie'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('ZA', 'Afrique du Sud'), ('KE', 'Kenya'), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('LR', 'Libéria'), ('CM', 'Cameroun'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('SL', 'Sierra-Leone'), ('GM', 'Gambie')], max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Commentaire',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=500, verbose_name='Raison du signalement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='page.comment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'db_table': 'signalement',
                'unique_together': {('comment', 'reporter')},
            },
        ),
    ]
