# Generated by Django 5.2.1 on 2025-10-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0032_alter_donation_donor_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecontact',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Lu'),
        ),
    ]
