# Generated by Django 5.2.1 on 2025-11-01 10:57

import uuid
from django.db import migrations, models


def refresh_all_public_ids(apps, schema_editor):
    model_names = [
        'Comment','Donation','EmailContent','FundingRequest','FundingRequestNotification','FundingRequestStatus',
        'FundingType','FundPayment','LossAlert','LossAlertNotification','LossAlertStatus','LossAlertType',
        'MessageContact','OptionalAlertDoc','OptionalFundingDoc','UserDetails'
    ]
    for name in model_names:
        Model = apps.get_model('page', name)
        for obj in Model.objects.all().iterator(chunk_size=500):
            obj.public_id = uuid.uuid4()
            obj.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0035_backfill_public_id'),
    ]

    operations = [
        migrations.RunPython(refresh_all_public_ids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='comment',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='emailcontent',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='fundingrequest',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='fundingrequestnotification',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='fundingrequeststatus',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='fundingtype',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='fundpayment',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lossalert',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lossalertnotification',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lossalertstatus',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lossalerttype',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='optionalalertdoc',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='optionalfundingdoc',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
