# Generated by Django 6.0.4 on 2026-05-04 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0038_backfill_location_fk_from_legacy_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Creation'), ('update', 'Modification'), ('delete', 'Suppression'), ('close', 'Cloture')], max_length=32)),
                ('model_name', models.CharField(max_length=100)),
                ('object_public_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('object_pk', models.CharField(blank=True, max_length=64)),
                ('object_label', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal action utilisateur',
                'verbose_name_plural': 'Journal actions utilisateurs',
                'db_table': 'user_action_log',
                'ordering': ('-created_at',),
            },
        ),
    ]
