# Generated by Django 6.0.4 on 2026-05-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0039_useractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcontent',
            name='receiver_email',
            field=models.TextField(blank=True, null=True, verbose_name='Beneficiaire'),
        ),
    ]
