# Generated by Django 5.2.1 on 2026-05-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0040_emailcontent_receiver_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundingrequest',
            name='amount_received',
        ),
        migrations.AddField(
            model_name='fundingrequest',
            name='amount_disbursed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant déboursé'),
        ),
        migrations.AddField(
            model_name='fundingrequest',
            name='amount_returned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant rétrocédé'),
        ),
        migrations.AddField(
            model_name='fundingrequest',
            name='amount_transferred',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant transféré'),
        ),
        migrations.AlterField(
            model_name='fundingrequest',
            name='funding_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Montant Financement'),
        ),
        migrations.AlterField(
            model_name='fundpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked')], default='Active', max_length=20),
        ),
    ]
