# Generated by Django 5.2.1 on 2026-05-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0041_remove_fundingrequest_amount_received_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundingrequest',
            name='amount_disbursed',
        ),
        migrations.RemoveField(
            model_name='fundingrequest',
            name='amount_returned',
        ),
        migrations.RemoveField(
            model_name='fundingrequest',
            name='amount_transferred',
        ),
        migrations.AddField(
            model_name='fundingrequest',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Montant reçu'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Montant'),
        ),
    ]
