# Generated by Django 6.0.4 on 2026-05-10 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0042_remove_fundingrequest_amount_disbursed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='page.commune', verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='prefecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='page.prefecture', verbose_name='Préfecture'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='quarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='page.quarter', verbose_name='Quartier'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='page.region', verbose_name='Région'),
        ),
    ]
