# Generated by Django 6.0 on 2026-04-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjomyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Transaction Djomy')),
                ('merchant_reference', models.CharField(db_index=True, max_length=255, verbose_name='Référence Marchand')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('currency', models.CharField(default='GNF', max_length=10, verbose_name='Devise')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('payment_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Paiement')),
                ('raw_payload', models.JSONField(blank=True, null=True, verbose_name='Payload Webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paiement Djomy',
                'verbose_name_plural': 'Paiements Djomy',
                'ordering': ['-created_at'],
            },
        ),
    ]
